#https://about.gitlab.com/blog/2017/09/12/vuejs-app-gitlab/

build site:
  image: node:lts
  stage: build
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-7 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

lint:
  stage: test
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-7 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
    - npx eslint . --ext .vue,.js,.jsx,.cjs,.mjs --ignore-path .gitignore
    - npx prettier --check src/

vitest:
  stage: test
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-7 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
    - pnpm run test